@baseUrl = http://js-post-api.herokuapp.com/api

# Students

# @name getAllStudents
GET {{baseUrl}}/students?_page=1&_limit=10&_sort=mark&_order=desc&name_like=Michale&gender=male

###

# @name getStudentById
GET {{baseUrl}}/students/RiX084F

###

# @name addNewStudent
POST {{baseUrl}}/students
Content-Type: application/json

{
  "name": "anh Hau cute",
  "age": 50,
  "mark": 10,
  "gender": "male",
  "city": "pt"
}

###

# @name updateStudent
PATCH {{baseUrl}}/students/u6V7vww
Content-Type: application/json

{
  "name": "Michale Test"
}

###

# @name removeStudent
DELETE {{baseUrl}}/students/u6V7vww